//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNorthernHandyManReDone11_3_18.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImageGroup()
        {
            this.ImageGroups1 = new HashSet<ImageGroup>();
        }
    
        public int Id { get; set; }
        public Nullable<int> GroupsId { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<bool> BeforeAfter { get; set; }
        public Nullable<bool> Before { get; set; }
        public Nullable<int> LinkedImage { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string Description { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageGroup> ImageGroups1 { get; set; }
        public virtual ImageGroup ImageGroup1 { get; set; }
    }
}
